/* Generated By:JavaCC: Do not edit this line. clikeConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface clikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MINLET = 1;
  /** RegularExpression Id. */
  int MAYLET = 2;
  /** RegularExpression Id. */
  int LETTER = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int UNDERSC = 6;
  /** RegularExpression Id. */
  int IDCHAR = 7;
  /** RegularExpression Id. */
  int CHAR = 8;
  /** RegularExpression Id. */
  int IBLOQUE = 9;
  /** RegularExpression Id. */
  int FBLOQUE = 10;
  /** RegularExpression Id. */
  int IPAREN = 11;
  /** RegularExpression Id. */
  int FPAREN = 12;
  /** RegularExpression Id. */
  int ICORCHE = 13;
  /** RegularExpression Id. */
  int FCORCHE = 14;
  /** RegularExpression Id. */
  int REFER = 15;
  /** RegularExpression Id. */
  int FINLN = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int SUM = 18;
  /** RegularExpression Id. */
  int RES = 19;
  /** RegularExpression Id. */
  int MUL = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int tBOOL = 22;
  /** RegularExpression Id. */
  int tCHAR = 23;
  /** RegularExpression Id. */
  int tINT = 24;
  /** RegularExpression Id. */
  int tID = 25;
  /** RegularExpression Id. */
  int tCONST = 26;
  /** RegularExpression Id. */
  int tCOMM = 27;
  /** RegularExpression Id. */
  int tVOID = 28;
  /** RegularExpression Id. */
  int tMAIN = 29;
  /** RegularExpression Id. */
  int tPRINT = 30;
  /** RegularExpression Id. */
  int tPRINTLN = 31;
  /** RegularExpression Id. */
  int tREAD = 32;
  /** RegularExpression Id. */
  int tREADLN = 33;
  /** RegularExpression Id. */
  int tRETURN = 34;
  /** RegularExpression Id. */
  int t2CHAR = 35;
  /** RegularExpression Id. */
  int t2INT = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<MINLET>",
    "<MAYLET>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<UNDERSC>",
    "<IDCHAR>",
    "<CHAR>",
    "<IBLOQUE>",
    "<FBLOQUE>",
    "<IPAREN>",
    "<FPAREN>",
    "<ICORCHE>",
    "<FCORCHE>",
    "<REFER>",
    "<FINLN>",
    "<ASSIGN>",
    "<SUM>",
    "<RES>",
    "<MUL>",
    "<DIV>",
    "\"bool\"",
    "\"char\"",
    "\"int\"",
    "<tID>",
    "<tCONST>",
    "\"//\"",
    "\"void\"",
    "\"main\"",
    "\"print\"",
    "\"println\"",
    "\"read\"",
    "\"readln\"",
    "\"return\"",
    "\"int2char\"",
    "\"char2int\"",
  };

}
