/* Generated By:JavaCC: Do not edit this line. clike.java */
package traductor;
import java.io.*;
//...

public class clike implements clikeConstants {
        //...

    public static void main(String[] args) {
        clike parser = null;

        try {
                if(args.length == 0) {
                                parser = new clike(System.in);
                        }
                        else {
                    parser = new clike(new java.io.FileInputStream(args[0]));                   // 0 puede que sea el nombre del propio ejecutable, cuidado
                        }
                        //Programa es el símbolo inicial de la gramática
                        parser.Programa();
                        //...
                        System.out.println("***** An\u00e1lisis terminado con \u00e9xito *****");
                }
                catch (java.io.FileNotFoundException e) {
                        System.err.println ("Fichero " + args[0] + " no encontrado.");
                }
                catch (TokenMgrError e) {
                System.err.println("LEX_ERROR: " + e.getMessage());
        }
                catch (ParseException e) {
                        System.err.println("PARSE_ERROR: " + e.getMessage());
                }
                catch (Exception e) {
                        System.err.println("ERROR: " + e.getMessage());
                }
        //...
    }

//------------ Símbolo inicial de la gramática. Para análisis léxico no hace falta más
  static final public void Programa() throws ParseException {
        Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tBOOL:
        jj_consume_token(tBOOL);
        break;
      case tCHAR:
        jj_consume_token(tCHAR);
        break;
      case tINT:
        jj_consume_token(tINT);
        break;
      case tCONST:
        jj_consume_token(tCONST);
        break;
      case tCOMM:
        jj_consume_token(tCOMM);
        break;
      case tVOID:
        jj_consume_token(tVOID);
        break;
      case tMAIN:
        jj_consume_token(tMAIN);
        break;
      case tID:
        jj_consume_token(tID);
        break;
      case tPRINT:
        jj_consume_token(tPRINT);
        break;
      case tPRINTLN:
        jj_consume_token(tPRINTLN);
        break;
      case tREAD:
        jj_consume_token(tREAD);
        break;
      case tREADLN:
        jj_consume_token(tREADLN);
        break;
      case tSTRING:
        jj_consume_token(tSTRING);
        break;
      case tRETURN:
        jj_consume_token(tRETURN);
        break;
      case t2CHAR:
        jj_consume_token(t2CHAR);
        break;
      case t2INT:
        jj_consume_token(t2INT);
        break;
      case tIBLOQUE:
        jj_consume_token(tIBLOQUE);
        break;
      case tFBLOQUE:
        jj_consume_token(tFBLOQUE);
        break;
      case tIPAREN:
        jj_consume_token(tIPAREN);
        break;
      case tFPAREN:
        jj_consume_token(tFPAREN);
        break;
      case tICORCHE:
        jj_consume_token(tICORCHE);
        break;
      case tFCORCHE:
        jj_consume_token(tFCORCHE);
        break;
      case tREFER:
        jj_consume_token(tREFER);
        break;
      case tFINLN:
        jj_consume_token(tFINLN);
        break;
      case tASSIGN:
        jj_consume_token(tASSIGN);
        break;
      case tSUM:
        jj_consume_token(tSUM);
        break;
      case tRES:
        jj_consume_token(tRES);
        break;
      case tMUL:
        jj_consume_token(tMUL);
        break;
      case tDIV:
        jj_consume_token(tDIV);
        break;
      case tIANG:
        jj_consume_token(tIANG);
        break;
      case tFANG:
        jj_consume_token(tFANG);
        break;
      case tNEQ:
        jj_consume_token(tNEQ);
        break;
      case tWHILE:
        jj_consume_token(tWHILE);
        break;
      case tIF:
        jj_consume_token(tIF);
        break;
      case tELSE:
        jj_consume_token(tELSE);
        break;
      case tEQ:
        jj_consume_token(tEQ);
        break;
      case tCOMMA:
        jj_consume_token(tCOMMA);
        break;
      case tORR:
        jj_consume_token(tORR);
        break;
      case tMOD:
        jj_consume_token(tMOD);
        break;
      case tNOT:
        jj_consume_token(tNOT);
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tIBLOQUE:
      case tFBLOQUE:
      case tIPAREN:
      case tFPAREN:
      case tICORCHE:
      case tFCORCHE:
      case tREFER:
      case tFINLN:
      case tASSIGN:
      case tSUM:
      case tRES:
      case tMUL:
      case tDIV:
      case tMOD:
      case tIANG:
      case tFANG:
      case tNEQ:
      case tEQ:
      case tORR:
      case tNOT:
      case tWHILE:
      case tIF:
      case tELSE:
      case tBOOL:
      case tCHAR:
      case tINT:
      case tCONST:
      case tCOMM:
      case tVOID:
      case tMAIN:
      case tPRINT:
      case tPRINTLN:
      case tREAD:
      case tREADLN:
      case tRETURN:
      case t2CHAR:
      case t2INT:
      case tID:
      case tSTRING:
      case tCOMMA:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public clikeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xfffff800,0xfffff800,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x7ffff,0x7ffff,};
   }

  /** Constructor with InputStream. */
  public clike(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public clike(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new clikeTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public clike(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new clikeTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public clike(clikeTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(clikeTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
