/* Generated By:JavaCC: Do not edit this line. clikeConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface clikeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int mLETTER = 5;
  /** RegularExpression Id. */
  int MLETTER = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int IDCHAR = 10;
  /** RegularExpression Id. */
  int tIBLOQUE = 11;
  /** RegularExpression Id. */
  int tFBLOQUE = 12;
  /** RegularExpression Id. */
  int tIPAREN = 13;
  /** RegularExpression Id. */
  int tFPAREN = 14;
  /** RegularExpression Id. */
  int tICORCHE = 15;
  /** RegularExpression Id. */
  int tFCORCHE = 16;
  /** RegularExpression Id. */
  int tREFER = 17;
  /** RegularExpression Id. */
  int tFINLN = 18;
  /** RegularExpression Id. */
  int tASSIGN = 19;
  /** RegularExpression Id. */
  int tSUM = 20;
  /** RegularExpression Id. */
  int tRES = 21;
  /** RegularExpression Id. */
  int tMUL = 22;
  /** RegularExpression Id. */
  int tDIV = 23;
  /** RegularExpression Id. */
  int tMOD = 24;
  /** RegularExpression Id. */
  int tIANG = 25;
  /** RegularExpression Id. */
  int tFANG = 26;
  /** RegularExpression Id. */
  int tNEQ = 27;
  /** RegularExpression Id. */
  int tEQ = 28;
  /** RegularExpression Id. */
  int tORR = 29;
  /** RegularExpression Id. */
  int tNOT = 30;
  /** RegularExpression Id. */
  int tWHILE = 31;
  /** RegularExpression Id. */
  int tIF = 32;
  /** RegularExpression Id. */
  int tELSE = 33;
  /** RegularExpression Id. */
  int tBOOL = 34;
  /** RegularExpression Id. */
  int tCHAR = 35;
  /** RegularExpression Id. */
  int tINT = 36;
  /** RegularExpression Id. */
  int tCONST = 37;
  /** RegularExpression Id. */
  int tCOMM = 38;
  /** RegularExpression Id. */
  int tVOID = 39;
  /** RegularExpression Id. */
  int tMAIN = 40;
  /** RegularExpression Id. */
  int tPRINT = 41;
  /** RegularExpression Id. */
  int tPRINTLN = 42;
  /** RegularExpression Id. */
  int tREAD = 43;
  /** RegularExpression Id. */
  int tREADLN = 44;
  /** RegularExpression Id. */
  int tRETURN = 45;
  /** RegularExpression Id. */
  int t2CHAR = 46;
  /** RegularExpression Id. */
  int t2INT = 47;
  /** RegularExpression Id. */
  int tID = 48;
  /** RegularExpression Id. */
  int tSTRING = 49;
  /** RegularExpression Id. */
  int tCOMMA = 50;
  /** RegularExpression Id. */
  int tBASURA = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<mLETTER>",
    "<MLETTER>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<IDCHAR>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"&\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"==\"",
    "\"||\"",
    "\"!\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"bool\"",
    "\"char\"",
    "\"int\"",
    "<tCONST>",
    "<tCOMM>",
    "\"void\"",
    "\"main\"",
    "\"print\"",
    "\"println\"",
    "\"read\"",
    "\"readln\"",
    "\"return\"",
    "\"int2char\"",
    "\"char2int\"",
    "<tID>",
    "<tSTRING>",
    "\",\"",
    "<tBASURA>",
  };

}
